image: markhobson/maven-chrome
 
stages:
  - test
  - allure

Test:
  stage: test
  allow_failure: true
  services:
    - name: selenium/standalone-chrome:latest
      alias: chrome
  script:
    - mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
  artifacts:
    when: always
    paths:
      - /target/allure-result
Allure report:
  stage: allure
  script: 
    - mvn allure:serve
  artifacts:
    paths:
      - /target/surefire-reports/*
    when: always
    expire_in: 1 h