stages:
  - Test
  - Report

Test:
  stage: Test
  image: markhobson/maven-chrome
  allow_failure: true
  services:
    - name: selenium/standalone-chrome:latest
      alias: chrome
  script:
    - mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
  # artifacts:
  #   when: always
  #   paths:
  #     - allure-report
  #   expire_in: 1 h

Report:
  stage: Report
  image: pradapjackie/allure-reports-generation:1.0
  artifacts:
    when: always
    paths:
     - allure-results
     - allure-report
    expire_in: 1 h
  script:
   - allure generate allure-results --clean -o allure-report
  when: always
  allow_failure: true