stages:
  - Test
  - Report

Test:
  stage: Test
  image: markhobson/maven-chrome
  allow_failure: true
  services:
    - name: selenium/standalone-chrome:latest
      alias: chrome
  script:
    - mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - target/allure-results
    expire_in: 1 h

Report:
  stage: Report
  image: pradapjackie/allure-reports-generation:1.0
  artifacts:
    when: always
    paths:
     - target/allure-results
     - allure-report
    expire_in: 1 h
  script:
   - allure generate target/allure-results --clean -o allure-report
   - echo 'Allure report lives here https://${CI_PAGES_DOMAIN}/testname40425/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/browse/allure-report/index.html'
  when: always
  allow_failure: true