image: markhobson/maven-chrome
 
stages:
  - Test
  - Report

Test:
  stage: Test
  allow_failure: true
  services:
    - name: selenium/standalone-chrome:latest
      alias: chrome
  script:
    - mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - target/allure-report
    expire_in: 1 h

Allure report:
  stage: Report
  script:
    - mkdir public
    - mv target/allure-report/* public
  artifacts:
    paths:
      - public
    when: always
    expire_in: 1 h