image: markhobson/maven-chrome
 
stages:
  - test
Integration tests with Allure:
  stage: test
  services:
    - name: selenium/standalone-chrome:latest
      alias: chrome
  allow_failure: true
  script:
    - mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
    - mvn allure:serve
  artifacts:
    when: always
    name: "Report"
    paths:
      - target/surefire-reports/*
    expire_in: 1 h