# .gitlab-ci.yml

stages:
  - selenium-tests

selenium-tests:
  stage: selenium-tests
  image: maven:latest
  script:
    - mvn clean test
  rules:
    - exists(".gitlab/schedule.yml")
  only:
    refs:
      - schedules
  tags:
    - selenium-runner
  when: always