image: markhobson/maven-chrome
 
stages:
  - Test
  - Report

Test:
  stage: Test
  allow_failure: true
  services:
    - name: selenium/standalone-chrome:latest
      alias: chrome
  script:
    # - mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
    - mvn clean install
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - target/allure-report
    expire_in: 1 h

Report:
  stage: Report
  image: pradapjackie/allure-reports-generation:1.0
  script:
    - mkdir public
    - mv target/allure-report/* public
  artifacts:
    when: always
    paths:
      - public
    expire_in: 1 h