image: markhobson/maven-chrome
 
stages:
  - test
 
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - apt-get update -qy
  - apt-get -y install zip unzip wget
  - mkdir chromeBrowser
  - echo 'VERSION OS'
  # - sw_vers
  - lsb_release -a
  - cd chromeBrowser
  - wget https://chromedriver.storage.googleapis.com/102.0.5005.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d '/chromeBrowser'
 
test:
  stage: test
  allow_failure: true
 
# Run the tests  
  script:
    - mvn $MAVEN_OPTS clean package
    - mvn clean test -Dselenide.headless=true
 
# Store artifacts
  artifacts:
    when: always
    name: "report"
    paths:
    - target/surefire-reports/*
    expire_in: 1 h