image: markhobson/maven-chrome
 
stages:
  - ui-test
 
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
 
ui-test:
  stage: ui-test
  services:
    - name: selenium/standalone-chrome:latest 
      alias: chrome
  allow_failure: true
 
# Run the tests  
  script:
    - mvn $MAVEN_OPTS clean package
    - mvn clean test -Dselenide.headless=true
 
# Store artifacts
  artifacts:
    when: always
    name: "report"
    paths:
    - target/surefire-reports/*
    expire_in: 1 h