image: markhobson/maven-chrome
 
stages:
  - Test

Test:
  stage: Test
  allow_failure: true
  services:
    - name: selenium/standalone-chrome:latest
      alias: chrome
  script:
    - mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
    - mvn allure:report
    - mkdir public
    - mv target/allure-report/* public
  artifacts:
    when: always
    paths:
      - public
    expire_in: 1 h