# .gitlab-ci.yml

stages:
  - test

before_script:
  - apt-get update
  - apt-get install -y libglib2.0-0 libnss3

selenium_tests:
  stage: test
  image: maven:latest
  script:
    - mvn clean test
  only:
    refs:
      - schedules
  tags:
    - selenium-runner
  when: always