# .gitlab-ci.yml

stages:
  - before
  - test
  - selenoid_stop

before_script:
  - apt-get update
  - apt-get install -y libglib2.0-0 libnss3 libxcb1

# selenoid:
#   stage: selenoid_start
#   image: aerokube/selenoid:latest-release
#   tags:
#     - selenium-runner
#   when: always
before:
  stage: before
  tags:
    - selenium-runner
  script: 
  - mkdir /etc/selenoid
  - cp /builds/testname40425/ProjectTest/browsers.json /etc/selenoid/browsers.json

selenium_tests:
  stage: test
  services:
    - name: aerokube/selenoid:latest-release
      alias: selenoid
  variables:
    SELENOID_URL: http://selenoid:4444/wd/hub
  image: maven:latest
  script:
    - mvn clean test -Dselenoid.remote.url=${SELENOID_URL}
  only:
    refs:
      - schedules
  tags:
    - selenium-runner
  when: always

selenoid_stop:
  stage: selenoid_stop
  image: aerokube/selenoid:latest-release
  script:
    - selenoid stop
  tags:
    - selenium-runner