image: markhobson/maven-chrome
 
stages:
  - Test
  - Generate-allure-report

Test:
  stage: Test
  allow_failure: true
  services:
    - name: selenium/standalone-chrome:latest
      alias: chrome
  script:
    - mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
    # - mvn allure:report
    # - mkdir public
    # - mv target/allure-report/* public
  artifacts:
    when: always
    paths:
      - allure-results
    expire_in: 1 h

before_script:    
- export MAVEN_HOME=/usr/local/apache-maven

Generate-allure-result:
  stage: Generate-allure-report
  image: pradapjackie/allure-reports-generation:1.0
  artifacts:
    paths:
     - allure-results
     - allure-report
    when: always
    expire_in: 1 days
  script:
    - $MAVEN_HOME/bin/mvn clean
    - mvn allure:report
  allow_failure: true
  rules:
   - when: always