# .gitlab-ci.yml

stages:
  - test

selenium_tests:
  stage: test
  services:
    - name: aerokube/selenoid:latest-release
      alias: selenoid
  variables:
    SELENOID_URL: http://selenoid:4444/wd/hub
  image: maven:latest
  script:
    - mvn clean test
  only:
    refs:
      - schedules
  tags:
    - selenium-runner
  when: always